---
- hosts: 127.0.0.1
  roles:
    - role: /root/wazuh-ansible/roles/wazuh/ansible-wazuh-manager
    - {role: /root/wazuh-ansible/roles/wazuh/ansible-filebeat, filebeat_output_logstash_hosts: '127.0.0.1'}
