---
logstash_create_config: true
logstash_input_beats: true

# You can introduce Multiples IPs
# elasticseacrh_network_host: ["Localhost1", "Localhost2", "Localhost3", ...]
elasticsearch_host: "{{ elasticsearch_network_host }}"

elasticsearch_http_port: "443"
elastic_stack_version: 6.7.0-1

logstash_install_java: true
