---
- name: RedHat/CentOS/Fedora | Install Elastic repo
  yum_repository:
    name: elastic_repo
    description: Elastic repository for 6.x packages
    baseurl: https://artifacts.elastic.co/packages/6.x/yum
    gpgkey: https://artifacts.elastic.co/GPG-KEY-elasticsearch
    gpgcheck: true

# - name: RedHat/CentOS/Fedora | Install Kibana
#   package: name=kibana-oss-{{ kibana_stack_version }} state=present
#   tags: install

- name: RedHat/CentOS/Fedora | Install Kibana
  yum:
    name: https://artifacts.elastic.co/downloads/kibana/kibana-oss-{{ kibana_stack_version }}-x86_64.rpm
    state: present