---
- name: rebuild cdb_lists
  command: /var/ossec/bin/ossec-makelists

- name: restart wazuh-manager
  service:
    name: wazuh-manager
    state: restarted
    enabled: true

- name: restart wazuh-api
  service:
    name: wazuh-api
    state: restarted
    enabled: true
  when:
    - not (ansible_distribution == 'CentOS' or ansible_distribution == 'RedHat' and ansible_distribution_major_version|int < 6)
